/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Deadline */

#ifndef _Included_Deadline
#define _Included_Deadline
#ifdef __cplusplus
extern "C" {
#endif
#undef Deadline_MIN_PRIORITY
#define Deadline_MIN_PRIORITY 1L
#undef Deadline_NORM_PRIORITY
#define Deadline_NORM_PRIORITY 5L
#undef Deadline_MAX_PRIORITY
#define Deadline_MAX_PRIORITY 10L
/*
 * Class:     Deadline
 * Method:    sayHi
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Deadline_sayHi
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Deadline
 * Method:    printPID
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Deadline_printPID
  (JNIEnv *, jobject);

/*
 * Class:     Deadline
 * Method:    sleep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Deadline_sleep
  (JNIEnv *, jobject);

/*
 * Class:     Deadline
 * Method:    scheduleAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Deadline_scheduleAll
  (JNIEnv *, jobject);

/*
 * Class:     Deadline
 * Method:    getPID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Deadline_getPID
  (JNIEnv *, jobject);

/*
 * Class:     Deadline
 * Method:    printSchedType
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Deadline_printSchedType
  (JNIEnv *, jobject);

/*
 * Class:     Deadline
 * Method:    setSchedType
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Deadline_setSchedType
  (JNIEnv *, jobject);

/*
 * Class:     Deadline
 * Method:    getchildPIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Deadline_getchildPIDs
  (JNIEnv *, jobject);

/*
 * Class:     Deadline
 * Method:    getParentPIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Deadline_getParentPIDs
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
